public enum Gaze_InputTypes
{
    START_BUTTON,

    A_BUTTON,
    A_BUTTON_DOWN,
    A_BUTTON_UP,
    A_BUTTON_TOUCH,
    A_BUTTON_UNTOUCH,

    B_BUTTON,
    B_BUTTON_DOWN,
    B_BUTTON_UP,
    B_BUTTON_TOUCH,
    B_BUTTON_UNTOUCH,


    X_BUTTON,
    X_BUTTON_DOWN,
    X_BUTTON_UP,
    X_BUTTON_TOUCH,
    X_BUTTON_UNTOUCH,


    Y_BUTTON,
    Y_BUTTON_DOWN,
    Y_BUTTON_UP,
    Y_BUTTON_TOUCH,
    Y_BUTTON_UNTOUCH,


    INDEX_LEFT,
    INDEX_LEFT_DOWN,
    INDEX_LEFT_UP,
    INDEX_LEFT_TOUCH,
    INDEX_LEFT_UNTOUCH,

    INDEX_RIGHT,
    INDEX_RIGHT_DOWN,
    INDEX_RIGHT_UP,
    INDEX_RIGHT_TOUCH,
    INDEX_RIGHT_UNTOUCH,

    THUMBREST_LEFT_TOUCH,
    THUMBREST_LEFT_UNTOUCH,
    THUMBREST_RIGHT_TOUCH,
    THUMBREST_RIGHT_UNTOUCH,

    HAND_LEFT,
    HAND_LEFT_DOWN,
    HAND_LEFT_UP,

    HAND_RIGHT,
    HAND_RIGHT_DOWN,
    HAND_RIGHT_UP,

    STICK_LEFT,
    STICK_LEFT_DOWN,
    STICK_LEFT_UP,
    STICK_LEFT_TOUCH,
    STICK_LEFT_UNTOUCH,

    STICK_RIGHT,
    STICK_RIGHT_DOWN,
    STICK_RIGHT_UP,
    STICK_RIGHT_TOUCH,
    STICK_RIGHT_UNTOUCH,

    PAD_LEFT_TOUCH_WEST,
    PAD_LEFT_TOUCH_EAST,
    PAD_LEFT_TOUCH_NORTH,
    PAD_LEFT_TOUCH_SOUTH,
    PAD_LEFT_TOUCH,

    PAD_RIGHT_TOUCH_WEST,
    PAD_RIGHT_TOUCH_EAST,
    PAD_RIGHT_TOUCH_NORTH,
    PAD_RIGHT_TOUCH_SOUTH,
    PAD_RIGHT_TOUCH,

    PAD_LEFT_PRESS_WEST,
    PAD_LEFT_PRESS_EAST,
    PAD_LEFT_PRESS_NORTH,
    PAD_LEFT_PRESS_SOUTH,

    PAD_RIGHT_PRESS_WEST,
    PAD_RIGHT_PRESS_EAST,
    PAD_RIGHT_PRESS_NORTH,
    PAD_RIGHT_PRESS_SOUTH,

    PAD_LEFT_RELEASE_WEST,
    PAD_LEFT_RELEASE_EAST,
    PAD_LEFT_RELEASE_NORTH,
    PAD_LEFT_RELEASE_SOUTH,

    PAD_LEFT_UNTOUCH_WEST,
    PAD_LEFT_UNTOUCH_EAST,
    PAD_LEFT_UNTOUCH_NORTH,
    PAD_LEFT_UNTOUCH_SOUTH,

    PAD_RIGHT_RELEASE_WEST,
    PAD_RIGHT_RELEASE_EAST,
    PAD_RIGHT_RELEASE_NORTH,
    PAD_RIGHT_RELEASE_SOUTH,

    PAD_RIGHT_UNTOUCH_WEST,
    PAD_RIGHT_UNTOUCH_EAST,
    PAD_RIGHT_UNTOUCH_NORTH,
    PAD_RIGHT_UNTOUCH_SOUTH,

    PAD_LEFT_UNTOUCH,
    PAD_RIGHT_UNTOUCH,
    NONE,
}