public enum Gaze_InputTypes
{
    START_BUTTON,

    A_BUTTON,
    A_BUTTON_DOWN,
    A_BUTTON_UP,

    B_BUTTON,
    B_BUTTON_DOWN,
    B_BUTTON_UP,

    X_BUTTON,
    X_BUTTON_DOWN,
    X_BUTTON_UP,

    Y_BUTTON,
    Y_BUTTON_DOWN,
    Y_BUTTON_UP,

    INDEX_LEFT,
    INDEX_LEFT_DOWN,
    INDEX_LEFT_UP,

    INDEX_RIGHT,
    INDEX_RIGHT_DOWN,
    INDEX_RIGHT_UP,

    HAND_LEFT,
    HAND_LEFT_DOWN,
    HAND_LEFT_UP,

    HAND_RIGHT,
    HAND_RIGHT_DOWN,
    HAND_RIGHT_UP,

    STICK_LEFT,
    STICK_LEFT_DOWN,
    STICK_LEFT_UP,

    STICK_RIGHT,
    STICK_RIGHT_DOWN,
    STICK_RIGHT_UP,

    PAD_LEFT_TOUCH_WEST,
    PAD_LEFT_TOUCH_EAST,
    PAD_LEFT_TOUCH_NORTH,
    PAD_LEFT_TOUCH_SOUTH,
    PAD_LEFT_TOUCH,

    PAD_RIGHT_TOUCH_WEST,
    PAD_RIGHT_TOUCH_EAST,
    PAD_RIGHT_TOUCH_NORTH,
    PAD_RIGHT_TOUCH_SOUTH,
    PAD_RIGHT_TOUCH,

    PAD_LEFT_PRESS_WEST,
    PAD_LEFT_PRESS_EAST,
    PAD_LEFT_PRESS_NORTH,
    PAD_LEFT_PRESS_SOUTH,
    
    PAD_RIGHT_PRESS_WEST,
    PAD_RIGHT_PRESS_EAST,
    PAD_RIGHT_PRESS_NORTH,
    PAD_RIGHT_PRESS_SOUTH,

    PAD_LEFT_RELEASE_WEST,
    PAD_LEFT_RELEASE_EAST,
    PAD_LEFT_RELEASE_NORTH,
    PAD_LEFT_RELEASE_SOUTH,

    PAD_RIGHT_RELEASE_WEST,
    PAD_RIGHT_RELEASE_EAST,
    PAD_RIGHT_RELEASE_NORTH,
    PAD_RIGHT_RELEASE_SOUTH,


    NONE,
}